### ISSUE TITLE
errores en la definición de los tipos

### ISSUE THREAD

**Issue by asCii88** [ciaa/Software-IDE#8]
Copio mensaje de embebidos32

Buenos días. 
Me pongo en contacto con ustedes porque me he encontrado con algunos problemas con el entorno de desarrollo para la CIAA.
Primero les comento que seguí los pasos de instalación y de creación de un nuevo proyecto, tal como se especifica en la página del Proyecto, con la diferencia de que elegí el rtos_example, en lugar de blinking, y que instalé en D:\ (Creo haber hecho los cambios de nombre de unidad donde hiciera falta).
Podría decirse que fueron realizados con éxito, ya que he podido realizar el build sin problema.
Sin embargo, posteriormente me puse a mirar los fuentes  y al abrir /modules/rtos/inc/Types.h el editor me marca automáticamente 19 errores, específicamente en la definición de los tipos, desde int8_t, hasta uint_fast32_t. 
Por otra parte, cuando quiero configurar el debug, siguiendo el tutorial, no encuentro el .exe correspondiente en /Firmware/Out/bin
Estaré muy agradecido por cualquier ayuda que me puedan brindar.

Atentamente,
Rodrigo Pardo

PS: Estoy corriendo Windows XP SP3

Copio respuesta:

Pablo Ridolfi <pabloridolfi@gmail.com>
Estimado,

Antes de entrar en la explicación, aclaro algo para vos y para todos: 
El Proyecto CIAA tiene sus repositorios hosteados en GitHub, que tiene un mecanismo de issues muy cómodo y fácil de usar. En este caso el issue corresponde a CIAA-IDE:
https://github.com/ciaa/Software-IDE/issues
Podés crear un nuevo issue ahí explicando lo que te pasa, así queda registrado, y nosotros te vamos a ir comentando por ese mismo medio, además los comentarios te van a llegar por mail.
Así como en este caso, los invito a todos a reportar este tipo de cosas en el repositorio que corresponda (si son issues de Hardware, Firmware, etc.), acá están todos:
https://github.com/ciaa
De esta manera todo queda registrado en forma ordenada y cualquiera puede acceder a ver los problemas que se presentan y cómo solucionarlos.

Ahora sí, al problema en cuestión:
Eclipse marca esos errores porque le falta configurar un include path. Andá a las propiedades del proyecto > C/C++ General > Paths and Symbols, pestaña Includes. Luego seleccioná GNU C en Languages, luego clic en Add... y ahí tenés que navegar hasta la carpeta include del toolchain. En Windows supongo que debe ser algo así, quizás varíe la versión o la ruta, fijate bien cómo lo tenés instalado:
C:\ciaa\GNU Tools ARM Embedded\4.8 2014q2\arm-none-eabi\include

Dale OK a todo y andá al menú Project > C/C++ Index > Rebuild.
Deberían desaparecerte los errores.

De todas formas esto no debería afectarte la compilación, ya que el Makefile es externo a Eclipse. Envianos tu Makefile.mine así como la salida de la consola, porque si no te aparece un .exe es porque hay un error o debés estar compilando un binario para la CIAA, no para simular en PC.

Saludos.

**Comment by asCii88** [comment]
Muchas gracias, Pablo. El instalador no me creó el directorio GNU Tools ARM Embedded ni encuentro ninguno parecido.
¿Dónde encuentro el Makefile.mine?

**Comment by jcecconi** [comment]
El compilador para arm el instalador lo pone en un path similar a cygwin\usr\arm-none-eabi
El .mine lo tenws en el raíz de firmware

**Comment by asCii88** [comment]
Perfecto. Agregué el directorio C:\CIAA\cygwin\usr\arm-none-eabi\arm-none-eabi\include, reconstruí el índice y ahora no me marca más esos errores. Sin embargo tengo otro, en el archivo C:\CIAA\Firmware\modules\drivers\cortexM4\lpc43xx\lpc4337\src\ciaaDriverAio.c
me pone:
Symbol 'ADC0_IRQn' could not be resolved	
Symbol 'ADC1_IRQn' could not be resolved	
Symbol 'DMA_IRQn' could not be resolved	

En el raíz del firmware tengo Makefile y Makefile.config nada más, el .mine no me aparece en la búsqueda tampoco.

**Comment by jcecconi** [comment]
http://www.proyecto-ciaa.com.ar/devwiki/doku.php?id=docu:fw:bm:make

Esta todo o casi todo documentado en la wiki...RTFM

**Comment by asCii88** [comment]
Estoy leyendo el FUCKING manual... pero el paso titulado "Debug con Windows" es anterior al link que me pasaste. ¿Cómo se supone que llegue a ese si encuentro una dificultad antes? El respeto, ante todo, me parece. 
Entonces, ¿es esperable que no aparezca el .exe en el directorio que se muestra acá http://www.proyecto-ciaa.com.ar/devwiki/doku.php?id=docu:fw:bm:ide:ide_win_debug si lo único que hice fue lo previo?
Muchas gracias.

**Comment by jcecconi** [comment]
Antes que nada, no lo tomes como una falta de respeto, va con onda. Ahora...

Evidentemente hay un error en el paso a paso, si nunca compilaste no vas a
tener el .exe (elemental) aunque si podes completar a mano el path al
futuro .exe, pero no creo valga la pena adelantarse.

Por otro lado, en

www.proyecto-ciaa.com.ar/devwiki/doku.php?id=docu:fw:bm:ide:ide_primeros_pasos

falta definir la variable BOARD con valor ciaa_sim_ia32 como se explica acá
(posterior, porque es para target en NXP, pero para x86 también corresponde
definirlo).

http://www.proyecto-ciaa.com.ar/devwiki/doku.php?id=docu:fw:bm:ide:ide_edu_ciaa_debug

sino, la compilación es al target x defecto, que no estoy seguro si es
x86...porque de haber sido, te tendria que haber aparecido el .exe si como
mencionas compiló correctamente.

Teniendo las variables PROJECT_PATH y BOARD definidas en el IDE, no hace
falta el .mine para Eclipse, aunque si para usarlo x consola con cygwin.

Por ultimo, te invito a solicitar un usuario para editar la wiki y corregir
los errores que encuentres, así como completar el FAQ con los problemas
típicos que encuentres, así se va avanzando con la documentación del
proyecto.

**Comment by mcerdeiro** [comment]
Se puede automatizar el instalador para que nada de esto sea necesario?
Osea poder instalar en d prio más low y poner los paths de eclipse para que
encuentre stdint bien? Ya que si es automático hasta nos ahorramos la
documentación :)

Saludos
Mariano

Saludos
Am 28.05.2015 17:57 schrieb "Juan Cecconi" <notifications@github.com>:

> Antes que nada, no lo tomes como una falta de respeto, va con onda.
> Ahora...
>
> Evidentemente hay un error en el paso a paso, si nunca compilaste no vas a
> tener el .exe (elemental) aunque si podes completar a mano el path al
> futuro .exe, pero no creo valga la pena adelantarse.
>
> Por otro lado, en
>
>
> www.proyecto-ciaa.com.ar/devwiki/doku.php?id=docu:fw:bm:ide:ide_primeros_pasos
>
> falta definir la variable BOARD con valor ciaa_sim_ia32 como se explica acá
> (posterior, porque es para target en NXP, pero para x86 también corresponde
> definirlo).
>
>
> http://www.proyecto-ciaa.com.ar/devwiki/doku.php?id=docu:fw:bm:ide:ide_edu_ciaa_debug
>
> sino, la compilación es al target x defecto, que no estoy seguro si es
> x86...porque de haber sido, te tendria que haber aparecido el .exe si como
> mencionas compiló correctamente.
>
> Teniendo las variables PROJECT_PATH y BOARD definidas en el IDE, no hace
> falta el .mine para Eclipse, aunque si para usarlo x consola con cygwin.
>
> Por ultimo, te invito a solicitar un usuario para editar la wiki y corregir
> los errores que encuentres, así como completar el FAQ con los problemas
> típicos que encuentres, así se va avanzando con la documentación del
> proyecto.
>
>

**Comment by mcerdeiro** [comment]
A un punto más. Por defecto el board de firmware debería ser ciaa_sim_ia32.
Si no es así alguien lo modificó y es un bug :(

Claro eso seria issue en firmware y no acá Hehe. Pero bueno

Saludos
Mariano
Am 28.05.2015 19:02 schrieb "Mariano Cerdeiro" <mcerdeiro@gmail.com>:

**Comment by mribelotta** [comment]
Eso ya no iria del lado de eclipse sino del lado del firmware, porque lo
que habria que tener, es, por cada proyecto de firmware la configuracón
correspondiente de eclipse o una configuración general para toda la carpeta
firmware.

Con crear el proyecto y copiar ".cproject" y ".project" suficientemente
modificados (TBD) al repo deberia bastar.

¿Que les parece la idea?

**Comment by mcerdeiro** [comment]
Hola Martín,

El firmware encuentra todo, por eso compila. El eclipse no encuentra stdint
y por eso muestro tipos en rojo.
Respecto al board por defecto si es un tema de firmware y no de Ide. Pero
lo que yo decía es que el installer configure bien los paths de eclipse.

Saludos
Mariano
Am 28.05.2015 19:09 schrieb "Martin Ribelotta" <notifications@github.com>:

**Comment by mribelotta** [comment]
Si, conosco el maldito problema de eclipse-cdt con los proyectos de
Makefile. Me ha dado y me sigue dando muchos quebraderos de cabeza.

Justamente por eso sugiero este workaround. El .cproject contiene toda esa
info de los PATH que luego usará eclipse para hacer el
autocompletado/code-index.

Luego el ".project" es necesario para que el IDE lo tome como un proyecto
en si.

El tema es que el eclipse en si, no falla, sino que el proyecto, creado a
travez de importar el directorio del Makefile no entiende nada de los PATH
de busqueda y hay que ponerlos a mano.

La real solución seria crear un plugin de eclipse de "Project Wizard" que
tomara el directorio git del firmware (local o remoto) y generara un
proyecto vacio o a partir de uno de los proyectos ya existentes con los
PATH correctamente inicializados.

Lamento no poder dedicarle casi nada de tiempo a esto porque a partir de
ahi verdaderamente tendriamos un IDE de la CIAA Firmware propiamente.

De todas formas, no creo que sea un workaround muy problematico el que
propongo.

**Comment by mribelotta** [comment]
Nota: Hay muchos workarounds:
http://stackoverflow.com/questions/2705947/with-eclipse-how-to-add-include-paths-and-libraries-for-all-your-c-c-project
http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.cdt.doc.user%2Freference%2Fcdt_u_prop_general_pns_libpath.htm

Pero todos deben hacerse con el proyecto ya creado, así que, de forma
técnica, es un problema de la creación del proyecto de eclipse antes que de
eclipse en si y es imposible tener eso en el instalador (no es información
del IDE sino del proyecto)

**Comment by mcerdeiro** [comment]
Claro seria copado. Osea tener un Wizzard de crear un proyecto ciaa. Así se
podría seleccionar en base a que ejemplo o empty. Osea resolvería mis esta
issue y además quedaría re cool... :)

Saludos
Mariano
Am 28.05.2015 19:19 schrieb "Martin Ribelotta" <notifications@github.com>:

**Comment by mribelotta** [comment]
Definitivamente a eso hay que apuntar, porque tener ".cproject" y
".project" en el Firmware ensucia mucho el asunto.

Yo he llegado hasta esto:
http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.cdt.doc.isv%2Fguide%2FprojectTemplateEngine%2FHowtodeveloptemplates.html

Pero no he tenido tiempo de seguir mucho mas allá, y por desgracia voy a
seguir así en los próximos dos/tres meses con apariciones esporádicas mías
y poco mas.

Alguno de anima a encarar esto? Realmente creo que es necesario mas allá de
lo "cool" que quede. Se requiere un fuerte skill en programación en java y
desarrollo de plugins en eclipse.

**Comment by mcerdeiro** [comment]
Hehe tener archivos de eclipse en firmware es un no go. Ni en pedo. Eso es
muy sucio y no acepto :)

Yo java cero. Yo soy c :) y creo ni tenemos nadie de java en el proyecto :(
yo quería hacer ya hace mucho un eclipse plugin para configurar OSEK de
forma gráfica pero no apareció nadie... :(

Saludos
Mariano
Am 28.05.2015 19:27 schrieb "Martin Ribelotta" <notifications@github.com>:

**Comment by mribelotta** [comment]
El 28 de mayo de 2015, 14:31, Mariano Cerdeiro <notifications@github.com>
escribió:

> Hehe tener archivos de eclipse en firmware es un no go. Ni en pedo. Eso es
> muy sucio y no acepto :)
>
> Mmmm si, por desgracia es la única forma "fácil" de hacerlo.
Podría hacerse algún script de bash que "creara" el proyecto a manopla a
partir del repo de git. (Un Makefile???) y tenerlo como parte del stack de
herramientas del ide, pero sigue siendo una solución "chacarera".


> Yo java cero. Yo soy c :) y creo ni tenemos nadie de java en el proyecto :(
> yo quería hacer ya hace mucho un eclipse plugin para configurar OSEK de
> forma gráfica pero no apareció nadie... :(
>
> La idea la sigo teniendo, pero quede en punto muerto por tiempos.
En cuanto a programación en Java, me defiendo y creo que muchos de las
listas también. Pero eso no basta para hacer plugins para eclipse.

Cada vez que me he puesto a hacer plugins para eclipse, termino aprendiendo
que cosas hago mal a la fuerza, supongo que hay alguna mejor manera de
hacer las cosas.

@Ariel (Lutemberg) ¿Se podría plantear esto como un proyecto para alguna
cátedra de software? Tiene toda la pinta de ser ideal para un proyecto de
fin de carrera o algo así.

Slds!

**Comment by mcerdeiro** [comment]
En firmware no pero por eso yo decía que el installer del Ide busque eso y
arme el proyecto al instalar, va luego de instalar el eclipse que arme el
proyecto.

En firmware no me parece ya que muchos no usan el Ide. Además de que es muy
sucio y no quiero files de eclipse en el firmware.

Si desde firmware podemos implementar un script que quedaría en modules
tools... Que te retorna lo que necesites saber como paths.

Pero ojo el path del stdint no lo sabe el firmware. Lo sabe el
compilador... :)

Saludos
Mariano
Am 28.05.2015 19:42 schrieb "Martin Ribelotta" <notifications@github.com>:

**Comment by mribelotta** [comment]
El 28 de mayo de 2015, 14:46, Mariano Cerdeiro <notifications@github.com>
escribió:

> En firmware no pero por eso yo decía que el installer del Ide busque eso y
> arme el proyecto al instalar, va luego de instalar el eclipse que arme el
> proyecto.
>
> En firmware no me parece ya que muchos no usan el Ide. Además de que es muy
> sucio y no quiero files de eclipse en el firmware.
>
> En firmware nadie usa IDE en forma general, de hecho, yo nunca use IDE
para programar "de verdad" pero ese es otro cuento ;-)


> Si desde firmware podemos implementar un script que quedaría en modules
> tools... Que te retorna lo que necesites saber como paths.
>
> Pero ojo el path del stdint no lo sabe el firmware. Lo sabe el
> compilador... :)
>
> Se le puede preguntar al compilador:
$ echo | arm-none-eabi-gcc -Xpreprocessor -v -E -x c - 2>&1|grep '> search'
-A 10
#include <...> search starts here:
 d:\programas\eclipse-ac6\plugins\fr.ac6.mcu.externaltools.arm-none.win32_1.1.0.201503101257\tools\compiler\bin\../lib/gcc/arm-none-eabi/4.8.4/include
 d:\programas\eclipse-ac6\plugins\fr.ac6.mcu.externaltools.arm-none.win32_1.1.0.201503101257\tools\compiler\bin\../lib/gcc/arm-none-eabi/4.8.4/include-fixed
 d:\programas\eclipse-ac6\plugins\fr.ac6.mcu.externaltools.arm-none.win32_1.1.0.201503101257\tools\compiler\bin\../lib/gcc/arm-none-eabi/4.8.4/../../../../arm-none-eabi/include
End of search list.

Ok, ya que no tenemos gente/tiempo para hacer un plugin de eclipse
podriamos hacer una tool del entorno para generar el proyecto a partir del
git.

¿Alguien se postea los .project y .cproject que le genera el proyecto de
Firmware bien configurado?

**Comment by asCii88** [comment]
Hola. Ahí agregué la variable de entorno BOARD al Eclipse con el valor que me dijiste @jcecconi 
Sin embargo, nada. Entonces me fijé cuál es la salida por consola que tengo, y parece que no me está tomando el parámetro que le paso al make (Está puesto make -C ${CIAA_Firmware_path} tal como dice el tutorial), porque dice: 
make -C 
/usr/bin/make: la opciÃ³n requiere un argumento -- C

De hecho, si en Propiedades -> C/C++ Build aprieto en Variables, no me aparece CIAA_Firmware_path para elegirla, como si no supiera a qué hace referencia. ¿Eso dónde debería configurarlo?

Por otra parte, me siguen saliendo errores de símbolos no reconocidos, a medida que voy abriendo distintos archivos de código:
Symbol 'ADC0_IRQn' could not be resolved	ciaaDriverAio.c	
Symbol 'ADC1_IRQn' could not be resolved	ciaaDriverAio.c	
Symbol 'DMA_IRQn' could not be resolved	ciaaDriverAio.c	
Symbol 'MODBUSR' could not be resolved	ciaaModbus_transport.c	
Symbol 'MODBUSR' could not be resolved	ciaaModbus_transport.c	
Symbol 'ReceiveTask' could not be resolved	uart_receive.c

**Comment by jcecconi** [comment]
Las variables globales se definen como dice acá
http://www.proyecto-ciaa.com.ar/devwiki/doku.php?id=docu:fw:bm:ide:ide_entorno

Si esta definida, en Propiedades -> C/C++ Build->Variables debería
aparecer, junto a las otras creadas

**Comment by jcecconi** [comment]
Incluso me parece que si usas el installer varias de estas var globales ya
no hacen falta, porque al momento de lanzar el eclipse hay un par de bash
que ponen en el path el toolchain de arm y el openocd. Por ejemplo para
ejecutar el debugger debería solo llamarse a openocd sin usar ninguna var
global.
Esto habría que probarlo.
Por otro lado el path al cfg del openocd quedo viejo, de cuando no estaba
la fsl. Este path debería salir automático y no ponerse a mano.
Según me comentaron si importas el dir FW al crear el proyecto, no
necesitas hacer el cambio del dir actual al hacer el make con -C. En cuyo
caso se evita un paso mas y definir otra var global. De nuevo todo esto hay
que probarlo y documentarlo en la wiki.
Saludos

**Comment by asCii88** [comment]
Muchas gracias por la respuesta. Vamos por buen camino. Ahora la consola me tira:
make -C "D:\\CIAA\\Firmware" 
make: se entra en el directorio '/cygdrive/d/CIAA/Firmware'
Makefile:218: /cygdrive/c/CIAA/Firmware/examples/rtos_example/mak/Makefile: No such file or directory
make: *** No hay ninguna regla para construir el objetivo '/cygdrive/c/CIAA/Firmware/examples/rtos_example/mak/Makefile'.  Alto.
make: se sale del directorio '/cygdrive/d/CIAA/Firmware'

Por supuesto que no existen, porque yo estoy trabajando en D:/ (No hay espacio en C, perdón). Creí haber reemplazado todas las C, por D. ¿Dónde se supone que está ese path?

**Comment by mcerdeiro** [comment]
el include esta en:
https://github.com/ciaa/Firmware/blob/master/Makefile#L224

donde dice:

include $(PROJECT_PATH)$(DS)mak$(DS)Makefile

osea el problema es que el PROJECT_PATH se esta pasando mal al make o dando
mal. no se si es un tema de ide o de donde, solo digo donde esta en el
firmware :)

**Comment by asCii88** [comment]
Hola. Vuelvo a comentar porque hice la instalación en una PC con Windows 7, por si no era el XP y sigo teniendo el mismo problema. Incluso esta vez estoy con todo en C:\CIAA y no en D:\ como antes...
¿Qué puedo hacer?

**Comment by asCii88** [comment]
Os_Cfg.h lo tuve que copiar de  /Firmware/modules/posix/test/utest/inc y pasó esa parte.
Ahora Os_Internal.h incluye a Os_Internal_Arch_Cfg.h pero de este solo está uno con extensión .php
Parece que eso pasa con otros varios archivos.

**Comment by jcecconi** [comment]
Me parece te está faltando hacer el "make generate" o en su defecto en el
"make clean" debes hacer "make clean_generate" para que se genere el OS en
base al .oil que configura el OSEK
Saludos

**Comment by asCii88** [comment]
¿Eso no se hace automáticamente al tildar Clean en Behaviour de C/C++ Build para las propiedades del proyecto, y poniendo en el campo de texto: clean_generate?

**Comment by jcecconi** [comment]
si haces un clean inicialmente antes del build, deberia luego del clean
hacer el generate. Podes verificarlo porque en /out/gen tenes los inc y src
que se generaron a partir de los php, y el .oil para tu target.
Saludos

2015-06-02 15:15 GMT-03:00 asCii88 <notifications@github.com>:

**Comment by asCii88** [comment]
Listo, ya está.

**Comment by mcerdeiro** [comment]
Hola,

mmm por que copiaste Os_Cfg.h de /Firmware/modules/posix/test/utest/inc a
otro lado? va lo podes hacer pero es un error. Ya que el archivo se debe
configurar para cada proyecto.

Si haces make generate se genera el archivo Os_Cfg.h para tu configuracion.
La misma esta en examples/<name>/etc/<name>.oil donde name es el nombre del
ejemplo, ya sea blinking o lo que sea :)

Se entiende?
Saludos.
Mariano.-


2015-06-02 20:04 GMT+02:00 asCii88 <notifications@github.com>:

**Comment by asCii88** [comment]
Ya lo deshice. Perdón, jaja. Hice el clean y etc desde cygwin y funcionó.
Evidentemente no anda del todo bien el IDE

**Comment by mcerdeiro** [comment]
Evidentemente no siempre :(

2015-06-02 20:37 GMT+02:00 asCii88 <notifications@github.com>:

> Ya lo deshice. Perdón, jaja. Hice el clean y etc desde cygwin y funcionó.
> Evidentemente no anda del todo bien el IDE
>
> El mar., 2 de junio de 2015 15:35, Mariano Cerdeiro <

**Comment by mribelotta** [comment]
El 2 de junio de 2015, 15:37, asCii88 <notifications@github.com> escribió:

> Ya lo deshice. Perdón, jaja. Hice el clean y etc desde cygwin y funcionó.
> Evidentemente no anda del todo bien el IDE
>
Que te hace? No podes generar la regla de "make generate"?
Eso tenes que hacerlo a mano porque no hay un proyecto del IDE que te la
genere a mano:
http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.cdt.doc.user%2Freference%2Fcdt_u_create_make_target.htm
No se si eso esta explicado en alguna parte.


>
> El mar., 2 de junio de 2015 15:35, Mariano Cerdeiro <

**Comment by asCii88** [comment]
Claro. No tenía idea de eso. Hice los clean y el generate desde la consola
de cygwin y recién ahí pude compilar.

**Comment by jcecconi** [comment]
En la regla del "clean" del IDE tenes que poner "clean_generate", y luego
hace efectivamente un clean para que los genere por primera vez, sino
siempre el build te va a fallar. Eso tenes que repetirlo si modificas el
.oil del RTOS. En la wiki al menos la parte del ide casi seguro figura, al
menos yo seguro lo habia puesto al principio.

**Comment by asCii88** [comment]
Claro. Hice eso, pero aun así no funcionó hasta que lo hice por consola.
Por eso pareciera no andar del todo bien :/

**Comment by jcecconi** [comment]
no puede ser....si te hace el clean, el clean_generate debe funcionar
igual. De hecho por consola estas haciendo eso mismo. Porqué no copias todo
lo que te tira en la consola DEL IDE al hacerlo.
