### ISSUE TITLE
Los archivos de /rtos/gen tienen extensión .php después de la que les corresponde

### ISSUE THREAD

**Issue by asCii88** [ciaa/Software-IDE#9]
Los archivos que se copian en esta carpeta al instalar el IDE con el archivo de instalación tienen extensión .php y por lo tanto no compilan los programas.

**Comment by mcerdeiro** [comment]
Hola, 

eso es correcto, ya que los archivos se generan al hacer

```
make generate
```

El OSEK-OS (RTOS) de la CIAA es un sistema operaetivo generado, el generador transforma los archivos .x.php a .x :)

Cierro el issue, igual a lo sumo la issue corresponderia a Firmware y no a IDE ya que el IDE Solo lo instala... algo de info de osek: http://proyecto-ciaa.com.ar/devwiki/doku.php?id=docu:fw:bm:modules:rtos
